<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="ESB_AccountSummary" targetNamespace="http://www.example.org/ESB_AccountSummary/" xmlns:esb="http://www.example.org/ESB_AccountSummary/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <generatedXSD location="ESB_AccountSummary_InlineSchema1.xsd"/>
        <binding hasEncoding="false" imported="true" name="ESB_AccountSummarySOAP" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  <wsdl:types>
    
          <xsd:schema targetNamespace="http://www.example.org/ESB_AccountSummary/" xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions">
<xsd:include schemaLocation="ESB_AccountSummary_InlineSchema1.xsd"/>
    </xsd:schema>
    </wsdl:types>
  <wsdl:message name="AccountSummaryRequest">
    <wsdl:part element="esb:AccountSummary" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="AccountSummaryResponse">
    <wsdl:part element="esb:AccountSummaryResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="ESB_AccountSummary">
    <wsdl:operation name="AccountSummary">
      <wsdl:input message="esb:AccountSummaryRequest"/>
      <wsdl:output message="esb:AccountSummaryResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ESB_AccountSummarySOAP" type="esb:ESB_AccountSummary">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="AccountSummary">
      <soap:operation soapAction="http://www.example.org/ESB_AccountSummary/AccountSummary"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ESB_AccountSummary">
    <wsdl:port binding="esb:ESB_AccountSummarySOAP" name="ESB_AccountSummarySOAP">
      <soap:address location="http://www.example.org/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>