<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="bankDetails" targetNamespace="http://fcubs.iflex.com/service/FCUBSAccService/QueryAccBal" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://fcubs.iflex.com/service/FCUBSAccService/QueryAccBal" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <generatedXSD location="bankDetails_InlineSchema1.xsd"/>
        <binding hasEncoding="false" imported="true" name="bankDetailsSOAP" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  <wsdl:types>
    
          <xsd:schema targetNamespace="http://fcubs.iflex.com/service/FCUBSAccService/QueryAccBal" xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions">
<xsd:include schemaLocation="bankDetails_InlineSchema1.xsd"/>
    </xsd:schema>
    </wsdl:types>
  <wsdl:message name="NewOperationRequest">
    <wsdl:part element="tns:FCUBS_REQ_ENV" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="NewOperationResponse">
    <wsdl:part element="tns:FCUBS_RES_ENV" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="bankDetails">
    <wsdl:operation name="NewOperation">
      <wsdl:input message="tns:NewOperationRequest"/>
      <wsdl:output message="tns:NewOperationResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="bankDetailsSOAP" type="tns:bankDetails">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="NewOperation">
      <soap:operation soapAction="http://fcubs.iflex.com/service/FCUBSAccService/QueryAccBal/NewOperation"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="bankDetails">
    <wsdl:port binding="tns:bankDetailsSOAP" name="bankDetailsSOAP">
      <soap:address location="http://localhost:7800/AccountDetailsQuery"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>