<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="RTSERVICE" targetNamespace="http://localhost:7800/RTSERVICE/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://localhost:7800/RTSERVICE/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <generatedXSD location="RTSERVICE_InlineSchema1.xsd"/>
        <binding hasEncoding="false" imported="true" name="RTSERVICESOAP" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  <wsdl:types>
    
          <xsd:schema targetNamespace="http://localhost:7800/RTSERVICE/" xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions">
<xsd:include schemaLocation="RTSERVICE_InlineSchema1.xsd"/>
    </xsd:schema>
    </wsdl:types>
  <wsdl:message name="RTSERVICERequest">
    <wsdl:part element="tns:RTSERVICE" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="RTSERVICEResponse">
    <wsdl:part element="tns:RTSERVICEResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="RTSERVICE">
    <wsdl:operation name="RTSERVICE">
      <wsdl:input message="tns:RTSERVICERequest"/>
      <wsdl:output message="tns:RTSERVICEResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="RTSERVICESOAP" type="tns:RTSERVICE">
  	<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  	<wsdl:operation name="RTSERVICE">
  		<soap:operation soapAction="http://localhost:7800/RTSERVICE/RTSERVICE"/>
  		<wsdl:input>
  			<soap:body use="literal"/>
  		</wsdl:input>
  		<wsdl:output>
  			<soap:body use="literal"/>
  		</wsdl:output>
  	</wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="RTSERVICE">
    <wsdl:port binding="tns:RTSERVICESOAP" name="RTSERVICESOAP">
      <soap:address location="http://localhost:7800/RTSERVICE"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>