<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="BlockingAmount" targetNamespace="http://www.example.org/BlockingAmount/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.example.org/BlockingAmount/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <generatedXSD location="BlockingAmount_InlineSchema1.xsd"/>
        <binding hasEncoding="false" imported="true" name="BlockingAmountSOAP" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  <wsdl:types>
    
          <xsd:schema targetNamespace="http://www.example.org/BlockingAmount/" xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions">
<xsd:include schemaLocation="BlockingAmount_InlineSchema1.xsd"/>
    </xsd:schema>
    </wsdl:types>
  <wsdl:message name="BlockAmuont_ServiceRequest">
    <wsdl:part element="tns:BlockAmuont_Service" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="BlockAmuont_ServiceResponse">
    <wsdl:part element="tns:BlockAmuont_ServiceResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="BlockingAmount">
    <wsdl:operation name="BlockAmuont_Service">
      <wsdl:input message="tns:BlockAmuont_ServiceRequest"/>
      <wsdl:output message="tns:BlockAmuont_ServiceResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="BlockingAmountSOAP" type="tns:BlockingAmount">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="BlockAmuont_Service">
      <soap:operation soapAction="http://www.example.org/BlockingAmount/BlockAmuont_Service"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="BlockingAmount">
    <wsdl:port binding="tns:BlockingAmountSOAP" name="BlockingAmountSOAP">
      <soap:address location="http://www.example.org/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>