<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="AccountBalEnq" targetNamespace="http://www.example.org/AccountBalEnq/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.example.org/AccountBalEnq/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <generatedXSD location="AccountBalEnq_InlineSchema1.xsd"/>
        <binding hasEncoding="false" imported="true" name="AccountBalEnqSOAP" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  <wsdl:types>
    
          <xsd:schema targetNamespace="http://www.example.org/AccountBalEnq/" xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions">
<xsd:include schemaLocation="AccountBalEnq_InlineSchema1.xsd"/>
    </xsd:schema>
    </wsdl:types>
  <wsdl:message name="QueryAccBalRequest">
    <wsdl:part element="tns:FCUBS_REQ_ENV" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="QueryAccBalResponse">
    <wsdl:part element="tns:QUERYACCBAL_IOFS_RES" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="AccountBalEnq">
    <wsdl:operation name="QueryAccBal">
      <wsdl:input message="tns:QueryAccBalRequest"/>
      <wsdl:output message="tns:QueryAccBalResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="AccountBalEnqSOAP" type="tns:AccountBalEnq">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="QueryAccBal">
      <soap:operation soapAction="http://www.example.org/AccountBalEnq/QueryAccBal"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="AccountBalEnq">
    <wsdl:port binding="tns:AccountBalEnqSOAP" name="AccountBalEnqSOAP">
      <soap:address location="http://localhost:7800/DashenBank_AccountBalanceEnquiry"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>