<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="FetchPaymentListService" targetNamespace="http://www.example.org/FetchPaymentListService/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.example.org/FetchPaymentListService/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="FetchPaymentListServiceSOAP" originalBindingStyle="document"/>
        <generatedXSD location="FetchPaymentListService_InlineSchema1.xsd"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  
  <wsdl:types>
    
          <xsd:schema targetNamespace="http://www.example.org/FetchPaymentListService/" xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions">
<xsd:include schemaLocation="FetchPaymentListService_InlineSchema1.xsd"/>
</xsd:schema>
    </wsdl:types>
  <wsdl:message name="FetchPaymentListRequest">
    <wsdl:part element="tns:FetchPaymentList" name="parameters">
    	<wsdl:documentation>fetch</wsdl:documentation></wsdl:part>
  </wsdl:message>
  <wsdl:message name="FetchPaymentListResponse">
    <wsdl:part element="tns:FetchPaymentListResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="FetchPaymentListService">
    <wsdl:operation name="FetchPaymentList">
      <wsdl:input message="tns:FetchPaymentListRequest"/>
      <wsdl:output message="tns:FetchPaymentListResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="FetchPaymentListServiceSOAP" type="tns:FetchPaymentListService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="FetchPaymentList">
      <soap:operation soapAction="http://www.example.org/FetchPaymentListService/FetchPaymentList"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="FetchPaymentListService">
    <wsdl:port binding="tns:FetchPaymentListServiceSOAP" name="FetchPaymentListServiceSOAP">
      <soap:address location="http://localhost:7800/FetchPayment"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>