<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="FCUBSCustomerService" targetNamespace="http://www.example.org/FCUBSCustomerService/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.example.org/FCUBSCustomerService/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="FCUBSCustomerServiceSOAP" originalBindingStyle="document"/>
        <generatedXSD location="FCUBSCustomerService_InlineSchema2.xsd"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  
  
  
  
  <wsdl:types>
    
          <xsd:schema targetNamespace="http://www.example.org/FCUBSCustomerService/" xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions">

<xsd:include schemaLocation="FCUBSCustomerService_InlineSchema2.xsd"/>
</xsd:schema>
    </wsdl:types>
  <wsdl:message name="CLOSEAMTBLK_FSFSRequest">
    <wsdl:part element="tns:CLOSEAMTBLK_FSFS" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="CLOSEAMTBLK_FSFSResponse">
    <wsdl:part element="tns:CLOSEAMTBLK_FSFSResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="FCUBSCustomerService">
    <wsdl:operation name="CLOSEAMTBLK_FSFS">
      <wsdl:input message="tns:CLOSEAMTBLK_FSFSRequest"/>
      <wsdl:output message="tns:CLOSEAMTBLK_FSFSResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="FCUBSCustomerServiceSOAP" type="tns:FCUBSCustomerService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="CLOSEAMTBLK_FSFS">
      <soap:operation soapAction="http://www.example.org/FCUBSCustomerService/CLOSEAMTBLK_FSFS"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="FCUBSCustomerService">
    <wsdl:port binding="tns:FCUBSCustomerServiceSOAP" name="FCUBSCustomerServiceSOAP">
      <soap:address location="http://localhost:7800/Unfreeze"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>